### ISSUE TITLE
Luminance crashes while attempting to sync

### ISSUE THREAD

**Issue by churusaa** [craigcabrey/luminance#20]
Running Arch Linux current as of 10:00 PM EDT October 12 2016 and second generation Hue bridge (sw ver 01035934, model BSB002) GTK, Python, and libraries installed and running recommend versions.

Behavior observed is that the application launches successfully (both as normal user and root) and prompts for user to select Hue bridge. Hue bridge is found and selected. Next prompt is to "Press link button to continue."

`~/.python_hue` is then populated with a username, and Luminance crashes. This is the full trace:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/luminance/application.py", line 133, in _setup_finished
    self._init()
  File "/usr/lib/python3.5/site-packages/luminance/application.py", line 114, in _init
    application=self
  File "/usr/lib/python3.5/site-packages/luminance/views/window.py", line 39, in __init__
    self.lights_page.add(FramedEntityList(self.bridge.get_light_objects('id').values()))
  File "/usr/lib/python3.5/site-packages/luminance/views/entity.py", line 27, in __init__
    self.list.add(ListBoxRow(entity))
  File "/usr/lib/python3.5/site-packages/luminance/views/entity.py", line 60, in __init__
    self.model.hue,
  File "/usr/lib/python3.5/site-packages/phue-0.8-py3.5.egg/phue.py", line 186, in hue
  File "/usr/lib/python3.5/site-packages/phue-0.8-py3.5.egg/phue.py", line 94, in _get
  File "/usr/lib/python3.5/site-packages/phue-0.8-py3.5.egg/phue.py", line 635, in get_light
KeyError: 'hue'
`

Subsequent attempts to launch the software fail at the step where Hue bridge selection is made (both as root and normal user, if ~/.python_hue is populated with a username by a past failed run.)

Prior to erasing ~/.python_hue, the error was...

`(luminance:6126): GLib-GIO-CRITICAL **: g_dbus_connection_emit_signal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed`
Twice, and 
`(luminance:6126): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch=ac4c97bc563245e8b84166df7342fcf8 --binary-syntax --close-stderr': Child process exited with code 1`

repeatedly.

Lampe seems to work alright, but I'm not sure what the difference is.

**Comment by PanderMusubi** [comment]
When syncing I get a similar runtime problem on Yakkety (without `~/.philips_hue`):

    $ luminance 
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/luminance/application.py", line 133, in _setup_finished
        self._init()
      File "/usr/lib/python3.5/site-packages/luminance/application.py", line 114, in _init
        application=self
      File "/usr/lib/python3.5/site-packages/luminance/views/window.py", line 39, in __init__
        self.lights_page.add(FramedEntityList(self.bridge.get_light_objects('id').values()))
      File "/usr/lib/python3.5/site-packages/luminance/views/entity.py", line 27, in __init__
        self.list.add(ListBoxRow(entity))
      File "/usr/lib/python3.5/site-packages/luminance/views/entity.py", line 60, in __init__
        self.model.hue,
      File "/usr/local/lib/python3.5/dist-packages/phue.py", line 186, in hue
        self._hue = self._get('hue')
      File "/usr/local/lib/python3.5/dist-packages/phue.py", line 94, in _get
        return self.bridge.get_light(self.light_id, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/phue.py", line 635, in get_light
        return state['state'][parameter]
    KeyError: 'hue'

Please let me know how to investigate this further or when to retest.

**Comment by PanderMusubi** [comment]
I have found the origin of this problem. I've added `print(state)` in file `/usr/local/lib/python3.5/dist-packages/phue.py` before line number 632 that has `if parameter == 'name':` The result was:

    ...
    {'type': 'Extended color light', 'name': 'Xxx', 'modelid': 'LCT001', 'uniqueid': '00:17:**:**:00:db:**:7a-0b', 'state': {'effect': 'none', 'bri': 254, 'alert': 'none', 'on': True, 'colormode': 'hs', 'xy': [0.4596, 0.4105], 'hue': 14910, 'reachable': False, 'sat': 144, 'ct': 369}, 'swversion': '66013187', 'manufacturername': 'Philips'}
    {'type': 'Extended color light', 'name': 'Xxx', 'modelid': 'LCT001', 'uniqueid': '00:17:**:**:00:db:**:7a-0b', 'state': {'effect': 'none', 'bri': 254, 'alert': 'none', 'on': True, 'colormode': 'hs', 'xy': [0.4596, 0.4105], 'hue': 14910, 'reachable': False, 'sat': 144, 'ct': 369}, 'swversion': '66013187', 'manufacturername': 'Philips'}
    {'type': 'Dimmable light', 'name': 'Yyy', 'modelid': 'LWB004', 'uniqueid': '00:17:**:**:00:e5:**:a7-0b', 'state': {'bri': 254, 'reachable': True, 'on': False, 'alert': 'none'}, 'swversion': '66012040', 'manufacturername': 'Philips'}
    {'type': 'Dimmable light', 'name': 'Yyy', 'modelid': 'LWB004', 'uniqueid': '00:17:**:**:00:e5:**:a7-0b', 'state': {'bri': 254, 'reachable': True, 'on': False, 'alert': 'none'}, 'swversion': '66012040', 'manufacturername': 'Philips'}

(Note that I masked some IDs with *.) As is can be seen in the last two lines there is no key 'hue' in key 'state' when key 'type' has value 'Dimmable light'. Please support this type of light.

**Comment by PanderMusubi** [comment]
A buggy workaround is adding the next two lines after line 633 with `return state[parameter]`

            elif parameter in ('hue', 'sat', ) and parameter not in state['state'].keys():
                return 0

**Comment by PanderMusubi** [comment]
A bugfix for this is greatly appreciated as many users will experience this error.

**Comment by craigcabrey** [comment]
Sorry for the silence, recently moved across the country. Starting to take a look at this again. Just pushed a  change ([`9e36c7d`](https://github.com/craigcabrey/luminance/commit/9e36c7d7bbd0e7e7e12d5466acfe0195f36ef787)) which should fix this problem.

**Comment by thinkbrown** [comment]
So, after encountering the same issue, I found that luminance in its current state does not support dimmable (that is to say, non color changing) bulbs, as it attempts to get the hue of each bulb, which dimmable bulbs do not have. 

```
Using local data
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/phue.py", line 855, in get_light
    return state['state'][parameter]
KeyError: 'hue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thinkbrown/build/luminance/luminance/application.py", line 133, in _setup_finished
    self._init()
  File "/home/thinkbrown/build/luminance/luminance/application.py", line 114, in _init
    application=self
  File "/home/thinkbrown/build/luminance/luminance/views/window.py", line 39, in __init__
    self.lights_page.add(FramedEntityList(self.bridge.get_light_objects('id').values()))
  File "/home/thinkbrown/build/luminance/luminance/views/entity.py", line 27, in __init__
    self.list.add(ListBoxRow(entity))
  File "/home/thinkbrown/build/luminance/luminance/views/entity.py", line 62, in __init__
    self.model.hue,
  File "/usr/lib/python3.6/site-packages/phue.py", line 196, in hue
    self._hue = self._get('hue')
  File "/usr/lib/python3.6/site-packages/phue.py", line 104, in _get
    return self.bridge.get_light(self.light_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/phue.py", line 859, in get_light
    % (parameter, light_id))
KeyError: 'Not a valid key, parameter hue is not associated with light 3)'
```
