### ISSUE TITLE
Claims phue is not installed, but it is installed (Kubuntu 19.04)

### ISSUE THREAD

**Issue by Turbulentarius** [craigcabrey/luminance#35]
Traceback (most recent call last):
  File "/usr/bin/luminance", line 26, in <module>
    from luminance.application import Application
  File "/usr/lib/python3.7/site-packages/luminance/application.py", line 11, in <module>
    import phue
ModuleNotFoundError: No module named 'phue'

**Comment by Turbulentarius** [comment]
Nevermind. Apparently there's different ways to install phue, and I used pip instead of pip3. Highly illogical. But It seems it is now working. So if you have this problem remember to:

pip3 install phue

However... It seems to be crashing after connecting with the bridge, so probably someone needs to update the script :-D
